// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/proto/crypto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CryptoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoRequest) Reset() {
	*x = CryptoRequest{}
	mi := &file_internal_proto_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoRequest) ProtoMessage() {}

func (x *CryptoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoRequest.ProtoReflect.Descriptor instead.
func (*CryptoRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *CryptoRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CryptoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cryptos       []*Crypto              `protobuf:"bytes,1,rep,name=cryptos,proto3" json:"cryptos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoResponse) Reset() {
	*x = CryptoResponse{}
	mi := &file_internal_proto_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoResponse) ProtoMessage() {}

func (x *CryptoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoResponse.ProtoReflect.Descriptor instead.
func (*CryptoResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *CryptoResponse) GetCryptos() []*Crypto {
	if x != nil {
		return x.Cryptos
	}
	return nil
}

type Crypto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MarketCap     float64                `protobuf:"fixed64,3,opt,name=marketCap,proto3" json:"marketCap,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,4,opt,name=currentPrice,proto3" json:"currentPrice,omitempty"`
	MarketCapRank int32                  `protobuf:"varint,5,opt,name=marketCapRank,proto3" json:"marketCapRank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Crypto) Reset() {
	*x = Crypto{}
	mi := &file_internal_proto_crypto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Crypto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crypto) ProtoMessage() {}

func (x *Crypto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_crypto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crypto.ProtoReflect.Descriptor instead.
func (*Crypto) Descriptor() ([]byte, []int) {
	return file_internal_proto_crypto_proto_rawDescGZIP(), []int{2}
}

func (x *Crypto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Crypto) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Crypto) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *Crypto) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *Crypto) GetMarketCapRank() int32 {
	if x != nil {
		return x.MarketCapRank
	}
	return 0
}

var File_internal_proto_crypto_proto protoreflect.FileDescriptor

const file_internal_proto_crypto_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/crypto.proto\x12\x06crypto\"+\n" +
	"\rCryptoRequest\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\":\n" +
	"\x0eCryptoResponse\x12(\n" +
	"\acryptos\x18\x01 \x03(\v2\x0e.crypto.CryptoR\acryptos\"\x9c\x01\n" +
	"\x06Crypto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1c\n" +
	"\tmarketCap\x18\x03 \x01(\x01R\tmarketCap\x12\"\n" +
	"\fcurrentPrice\x18\x04 \x01(\x01R\fcurrentPrice\x12$\n" +
	"\rmarketCapRank\x18\x05 \x01(\x05R\rmarketCapRank2\x98\x01\n" +
	"\rCryptoService\x12>\n" +
	"\rGetTopCryptos\x12\x15.crypto.CryptoRequest\x1a\x16.crypto.CryptoResponse\x12G\n" +
	"\x12StreamCryptoUpdate\x12\x15.crypto.CryptoRequest\x1a\x16.crypto.CryptoResponse(\x010\x01B>Z<github.com/mouravitor313/List-Crypto-Currency/internal/protob\x06proto3"

var (
	file_internal_proto_crypto_proto_rawDescOnce sync.Once
	file_internal_proto_crypto_proto_rawDescData []byte
)

func file_internal_proto_crypto_proto_rawDescGZIP() []byte {
	file_internal_proto_crypto_proto_rawDescOnce.Do(func() {
		file_internal_proto_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_crypto_proto_rawDesc), len(file_internal_proto_crypto_proto_rawDesc)))
	})
	return file_internal_proto_crypto_proto_rawDescData
}

var file_internal_proto_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_crypto_proto_goTypes = []any{
	(*CryptoRequest)(nil),  // 0: crypto.CryptoRequest
	(*CryptoResponse)(nil), // 1: crypto.CryptoResponse
	(*Crypto)(nil),         // 2: crypto.Crypto
}
var file_internal_proto_crypto_proto_depIdxs = []int32{
	2, // 0: crypto.CryptoResponse.cryptos:type_name -> crypto.Crypto
	0, // 1: crypto.CryptoService.GetTopCryptos:input_type -> crypto.CryptoRequest
	0, // 2: crypto.CryptoService.StreamCryptoUpdate:input_type -> crypto.CryptoRequest
	1, // 3: crypto.CryptoService.GetTopCryptos:output_type -> crypto.CryptoResponse
	1, // 4: crypto.CryptoService.StreamCryptoUpdate:output_type -> crypto.CryptoResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_crypto_proto_init() }
func file_internal_proto_crypto_proto_init() {
	if File_internal_proto_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_crypto_proto_rawDesc), len(file_internal_proto_crypto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_crypto_proto_goTypes,
		DependencyIndexes: file_internal_proto_crypto_proto_depIdxs,
		MessageInfos:      file_internal_proto_crypto_proto_msgTypes,
	}.Build()
	File_internal_proto_crypto_proto = out.File
	file_internal_proto_crypto_proto_goTypes = nil
	file_internal_proto_crypto_proto_depIdxs = nil
}
